name: Publish NuGet Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Publish HttpCat
        id: publish-httpcat
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/Flandre.Plugins.HttpCat/Flandre.Plugins.HttpCat.csproj
          PACKAGE_NAME: Flandre.Plugins.HttpCat
          VERSION_FILE_PATH: src/Flandre.Plugins.HttpCat/Flandre.Plugins.HttpCat.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: Publish WolframAlpha
        id: publish-wolframalpha
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/Flandre.Plugins.WolframAlpha/Flandre.Plugins.WolframAlpha.csproj
          PACKAGE_NAME: Flandre.Plugins.WolframAlpha
          VERSION_FILE_PATH: src/Flandre.Plugins.WolframAlpha/Flandre.Plugins.WolframAlpha.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: Publish BaiduTranslate
        id: publish-baidutranslate
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/Flandre.Plugins.BaiduTranslate/Flandre.Plugins.BaiduTranslate.csproj
          PACKAGE_NAME: Flandre.Plugins.BaiduTranslate
          VERSION_FILE_PATH: src/Flandre.Plugins.BaiduTranslate/Flandre.Plugins.BaiduTranslate.csproj
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
